### ISSUE TITLE
NoMethodError: undefined method `days' for 30:Fixnum error while performing backup

### ISSUE THREAD

**Issue by xxxazxxx** [meskyanichi/backup#640]
````
aurum git:(master) ✗ RAILS_ENV=development backup perform -t db_backup
[2015/03/17 12:46:07][error] CLI::Error
[2015/03/17 12:46:07][error] --- Wrapped Exception ---
[2015/03/17 12:46:07][error] NoMethodError: undefined method `days' for 30:Fixnum
[2015/03/17 12:46:07][error] (erb):40:in `<main>'
[2015/03/17 12:46:07][error] /home/admin/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `eval'
[2015/03/17 12:46:07][error] /home/admin/.rvm/rubies/ruby-2.1.1/lib/ruby/2.1.0/erb.rb:850:in `result'
[2015/03/17 12:46:07][error] /home/admin/Backup/models/db_backup.rb:8:in `block in load'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/config.rb:48:in `instance_eval'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/config.rb:48:in `block in load'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/config.rb:47:in `each'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/config.rb:47:in `load'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/cli.rb:129:in `perform'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/bin/backup:5:in `<top (required)>'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/bin/backup:23:in `load'
[2015/03/17 12:46:07][error] /home/admin/.rvm/gems/ruby-2.1.1@gl/bin/backup:23:in `<main>'
````

**Comment by tombruijn** [comment]
Can you post some basic information about your config? There are so many places this can go wrong.

Post:

- your global config file
- your model file
- do you use a gemfile?
- is backup in the same gemfile as your rails project?

**Comment by xxxazxxx** [comment]
* Can you pls inform me which is the global config file you are talking about?
* db_backup.rb file
````
require 'yaml'
require 'erb'

rails_env       = ENV['RAILS_ENV'] || 'development'
database_yml    = File.expand_path('../../../ror/aurum/config/database.yml', __FILE__)
db_config       = YAML.load_file(database_yml)[rails_env]
application_yml = File.expand_path('../../../ror/aurum/config/application.yml', __FILE__)
app_config      = YAML.load(ERB.new(File.read(application_yml)).result)[rails_env]['backup']


# encoding: utf-8

##
# Backup Generated: db_backup
# Once configured, you can run the backup with the following command:
#
# $ backup perform -t db_backup [-c <path_to_configuration_file>]
#
# For more information about Backup's components, see the documentation at:
# http://meskyanichi.github.io/backup
#
Model.new(:db_backup, 'Description for db_backup') do

  ##
  # PostgreSQL [Database]
  #
  database PostgreSQL do |db|
    # To dump all databases, set `db.name = :all` (or leave blank)
    db.name               = db_config['database']
    db.username           = db_config['username']
    db.password           = db_config['password']
    db.host               = "localhost"
    db.port               = 5432
    db.socket             = "/tmp/pg.sock"
    # When dumping all databases, `skip_tables` and `only_tables` are ignored.
    db.skip_tables        = ["skip", "these", "tables"]
    db.only_tables        = ["only", "these", "tables"]
    db.additional_options = ["-xc", "-E=utf8"]
  end

#=begin
  ##
  # Amazon Simple Storage Service [Storage]
  #
  store_with S3 do |s3|
    # AWS Credentials
    s3.access_key_id     = app_config['connection_settings']['aws_access_key_id']
    s3.secret_access_key = app_config['connection_settings']['aws_secret_access_key']
    # Or, to use a IAM Profile:
    # s3.use_iam_profile = true

    s3.region            = app_config['connection_settings']['region']
    s3.bucket            = app_config['bucket']
    s3.path              = "/ivmm/#{rails_env}"
    s3.days_to_keep      = 50.days
  end
#=end

  # SCP (Secure Copy) [Storage]
  store_with SCP do |server|
    server.username   = app_config['backup_username']
    server.password   = app_config['backup_password']
    server.ip         = app_config['backup_ip']
    server.port       = app_config['backup_port']
    server.path       = app_config['backup_path']
    server.keep       = 5000
  end

end
````

* yes I use a gemfile but backup isn't present in gemfile. It's been installed via gem install backup
* no gemfile doesn't have backup gem. Its installed separately
* RAILS_ENV specifies the environment to be backup up.

Thanks a lot @tombruijn

**Comment by tombruijn** [comment]
@xxxazxxx 

- the global config file I was talking about is `config.rb` in the `~/Backup` dir.
- `s3.days_to_keep      = 50.days`
  - Try removing the `.days` part. That only works when you include ActiveSupport, which I don't recommend, but Backup also won't work with it. It expects a simple integer.
  - I see that part is commented out?

**Comment by xxxazxxx** [comment]
@tombruijn Thanks for your response. The application.yml which I was loading had 30.days for session. I removed days from it & I'm getting the following error now.
````
✗ backup perform -t db_backup
[2015/03/22 13:55:24][info] Performing Backup for 'Description for db_backup (db_backup)'!
[2015/03/22 13:55:24][info] [ backup 4.1.7 : ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux] ]
[2015/03/22 13:55:24][warn] Cleaner::Error: Cleanup Warning
[2015/03/22 13:55:24][warn]   The temporary packaging folder still exists!
[2015/03/22 13:55:24][warn]   '/home/admin/Backup/.tmp/db_backup'
[2015/03/22 13:55:24][warn]   It will now be removed.
[2015/03/22 13:55:24][warn]   
[2015/03/22 13:55:24][warn]   Please check the log for messages and/or your notifications
[2015/03/22 13:55:24][warn]   concerning this backup: 'Description for db_backup (db_backup)'
[2015/03/22 13:55:24][warn]   The temporary files which had to be removed should not have existed.
[2015/03/22 13:55:24][info] Database::PostgreSQL Started...
[2015/03/22 13:55:24][error] Model::Error: Backup for Description for db_backup (db_backup) Failed!
[2015/03/22 13:55:24][error] --- Wrapped Exception ---
[2015/03/22 13:55:24][error] Database::PostgreSQL::Error: Dump Failed!
[2015/03/22 13:55:24][error]   Pipeline STDERR Messages:
[2015/03/22 13:55:24][error]   (Note: may be interleaved if multiple commands returned error messages)
[2015/03/22 13:55:24][error]   
[2015/03/22 13:55:24][error]   sh: 1: cannot open %=: No such file
[2015/03/22 13:55:24][error]   The following system errors were returned:
[2015/03/22 13:55:24][error]   Errno::ENOENT: No such file or directory - 'pg_dump' returned exit code: 2
[2015/03/22 13:55:24][error] 
[2015/03/22 13:55:24][error] Backtrace:
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/database/postgresql.rb:72:in `perform!'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/model.rb:269:in `each'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/model.rb:269:in `block in perform!'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/model.rb:268:in `each'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/model.rb:268:in `perform!'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/lib/backup/cli.rb:156:in `perform'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/gems/backup-4.1.7/bin/backup:5:in `<top (required)>'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/bin/backup:23:in `load'
[2015/03/22 13:55:24][error]   /home/admin/.rvm/gems/ruby-2.1.1@gl/bin/backup:23:in `<main>'
[2015/03/22 13:55:24][warn] Cleaner::Error: Cleanup Warning
[2015/03/22 13:55:24][warn]   The temporary packaging folder still exists!
[2015/03/22 13:55:24][warn]   '/home/admin/Backup/.tmp/db_backup'
[2015/03/22 13:55:24][warn]   This folder may contain completed Archives and/or Database backups.
[2015/03/22 13:55:24][warn]   
[2015/03/22 13:55:24][warn]   Make sure you check these files before the next scheduled backup for
[2015/03/22 13:55:24][warn]   'Description for db_backup (db_backup)'
[2015/03/22 13:55:24][warn]   These files will be removed at that time!
````

**Comment by xxxazxxx** [comment]
@tombruijn I was able to fix it. The YML files which i was loading needed rails environment to be loaded to get the right database & application keys.

````
development:
  adapter: postgresql
  encoding: unicode
  database: <%= Rails.application.config.settings.db_name %>_development
  pool: 5
  username: xx
  password: xx
  host: localhost
````
I want to backup files never to expire. I want them to exist unless I manually delete them. How can I do it?
